service: loan-calculator-serverless

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 256
  timeout: 10
  environment:
    NODE_ENV: ${opt:stage, 'dev'}

functions:
  calculateLoanRates:
    handler: handler.getRateDetails
    events:
      - http:
          path: calculate
          method: post
          cors: true
    description: "Calculate loan payment schedules and rates"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000